name: Build and deploy web game

on:
  push:
    branches: [develop]
  pull_request:
    branches: [recette, main]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: "globomantics-web-game" # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: "6.0"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: "Vérification de la version de dotnet"
        run: |
          if [ $DOTNET_VERSION != "6.0" ]
          then
            echo "La version de dotnet ne permet pas de poursuivre ce workflow"
            exit 1
          fi

  analyse-codeQL:
    needs: checks
    if: success()
    uses: ./.github/workflows/codeql-analysis.yml

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: analyse-codeQL
    steps:
      - uses: actions/checkout@main

      - name: "Setup .NET Core"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: "Build app package"
        run: |
          dotnet restore '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/src/web-game/Globomantics.sln'
          dotnet build '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/src/web-game/Globomantics.sln' --configuration Release
          dotnet publish '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/src/web-game/Globomantics.sln' -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/app-package'
